import { useCallback, useEffect, useRef } from "react";
import { BOARD_GRID_SIZE, type BoardSurface, type BoardViewport } from "./boardTypes";
import { ISO_COL, ISO_ROW_HEIGHT } from "./geometry";

/** The board's paper: plain, 2D graph, or isometric (3D triangle) - drawn onto one viewport-sized
 * canvas that sits behind the world layer.
 *
 * Deliberately a canvas rather than a CSS repeating-gradient background. Graph paper alone tiles
 * fine in CSS, but an isometric lattice's repeat period is a *sheared* cell, and a rectangular
 * `background-size` tile can't hold three line families in phase with each other once zoom scales
 * it - the diagonals visibly break at tile seams and drift away from where snapToSurface believes
 * the lattice is. Drawing the lines directly means the background is computed from exactly the same
 * constants the snapping uses (ISO_COL / ISO_ROW_HEIGHT / BOARD_GRID_SIZE), so a snapped point is
 * always on a visible line by construction.
 *
 * Sizing follows SketchLayer's precedent: the canvas covers the *viewport* only, never the world.
 * An infinite canvas has no finite extent to render, and a "large enough to feel infinite" stand-in
 * would be a composited layer whose recomposite cost scales with its area. Panning redraws instead
 * of translating a huge layer - only the visible slice is ever rasterized, so cost is bounded by
 * screen size no matter how far out the user zooms. */
export function BoardBackground({
  surface,
  viewport,
  width,
  height,
}: {
  surface: BoardSurface;
  viewport: BoardViewport;
  width: number;
  height: number;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");
    if (!canvas || !ctx || width === 0 || height === 0) return;

    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.round(width * dpr);
    canvas.height = Math.round(height * dpr);
    canvas.style.width = `${width}px`;
    canvas.style.height = `${height}px`;
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, width, height);
    if (surface === "plain") return;

    const styles = getComputedStyle(canvas);
    const minor = styles.getPropertyValue("--board-grid-minor").trim() || "rgba(120,120,130,0.18)";
    const major = styles.getPropertyValue("--board-grid-major").trim() || "rgba(120,120,130,0.34)";

    const { zoom, x: originX, y: originY } = viewport;
    // World coordinate of each viewport edge - the span every line family below is generated
    // across, so only lines that can actually be seen are ever emitted.
    const worldLeft = originX;
    const worldTop = originY;
    const worldRight = originX + width / zoom;
    const worldBottom = originY + height / zoom;
    const sx = (wx: number) => (wx - originX) * zoom;
    const sy = (wy: number) => (wy - originY) * zoom;

    // Below roughly a third of natural size the minor lines collapse into a solid wash that reads
    // as noise rather than grid, so they're dropped and only the majors (graph) or a sparser
    // lattice (isometric) survive - the same "thin out as you zoom out" behaviour a map has.
    const showMinor = zoom > 0.34;

    ctx.lineWidth = 1;

    if (surface === "graph") {
      const drawFamily = (step: number, color: string) => {
        ctx.strokeStyle = color;
        ctx.beginPath();
        for (let wx = Math.floor(worldLeft / step) * step; wx <= worldRight; wx += step) {
          // The 0.5 offset puts a 1px stroke on a device-pixel boundary instead of straddling two,
          // which is the difference between crisp hairlines and a uniformly blurry grid.
          const px = Math.round(sx(wx)) + 0.5;
          ctx.moveTo(px, 0);
          ctx.lineTo(px, height);
        }
        for (let wy = Math.floor(worldTop / step) * step; wy <= worldBottom; wy += step) {
          const py = Math.round(sy(wy)) + 0.5;
          ctx.moveTo(0, py);
          ctx.lineTo(width, py);
        }
        ctx.stroke();
      };
      if (showMinor) drawFamily(BOARD_GRID_SIZE, minor);
      // Real graph paper's major/minor division every 5 cells - what makes it readable at a glance
      // instead of a flat wash, and what gives a zoomed-out board any structure once minors drop.
      drawFamily(BOARD_GRID_SIZE * 5, major);
      return;
    }

    // Isometric. Vertical lines plus the two 30deg families, each generated by its intercept so the
    // spacing is exact rather than accumulated. A 30deg line is `y = +/-slope * x + c`; stepping `c`
    // by ISO_ROW_HEIGHT * 2 (the lattice's vertical period) reproduces the printed paper exactly.
    const slope = ISO_ROW_HEIGHT / ISO_COL;
    ctx.strokeStyle = showMinor ? minor : major;
    ctx.beginPath();

    const colStep = showMinor ? ISO_COL : ISO_COL * 4;
    for (let wx = Math.floor(worldLeft / colStep) * colStep; wx <= worldRight; wx += colStep) {
      const px = Math.round(sx(wx)) + 0.5;
      ctx.moveTo(px, 0);
      ctx.lineTo(px, height);
    }

    const interceptStep = (showMinor ? 1 : 4) * ISO_ROW_HEIGHT * 2;
    for (const dir of [1, -1]) {
      // Intercept range that can touch the viewport: c = y - dir*slope*x evaluated at the two
      // x-extremes bounds every line crossing the visible rect.
      const cAtLeft = worldTop - dir * slope * worldLeft;
      const cAtRight = worldTop - dir * slope * worldRight;
      const span = worldBottom - worldTop;
      const cMin = Math.min(cAtLeft, cAtRight);
      const cMax = Math.max(cAtLeft, cAtRight) + span;
      for (let c = Math.floor(cMin / interceptStep) * interceptStep; c <= cMax; c += interceptStep) {
        ctx.moveTo(sx(worldLeft), sy(dir * slope * worldLeft + c));
        ctx.lineTo(sx(worldRight), sy(dir * slope * worldRight + c));
      }
    }
    ctx.stroke();
  }, [surface, viewport, width, height]);

  useEffect(() => {
    draw();
  }, [draw]);

  return <canvas ref={canvasRef} className="board-background" aria-hidden="true" />;
}
